import type { Cookie, CookieSet } from './schema';

const COOKIE_DETAILS = {
  pistachio: {
    subtitle: 'Фисташка · малина',
    description:
      'Фисташковое печенье с ягодной начинкой — баланс ореховой сливочности и кислинки ягод.',
    structure: 'Хрустящая корочка, тягучая серединка с ягодным центром.',
    composition: 'Мука, сливочное масло, фисташковая паста, малина, сахар, яйцо, соль.',
    nutrition: { calories: 475, protein: 14, fat: 23, carbs: 57 },
  },
  ferrero: {
    subtitle: 'Фундук · шоколад',
    description: 'Классика в духе Ferrero — лесной орех, шоколад и хруст.',
    structure: 'Плотное NY-cookie с хрустящими включениями и мягким центром.',
    composition: 'Мука, фундук, какао, сливочное масло, сахар, яйцо, ваниль.',
    nutrition: { calories: 510, protein: 12, fat: 28, carbs: 55 },
  },
  lemon: {
    subtitle: 'Лимон · ягоды',
    description: 'Лимонная свежесть с ягодным акцентом — лёгкий и яркий вкус.',
    structure: 'Мягкое тесто с цитрусовой нотой и ягодной начинкой.',
    composition: 'Мука, лимон, малина, сливочное масло, сахар, яйцо.',
    nutrition: { calories: 430, protein: 11, fat: 20, carbs: 58 },
  },
  biscoff: {
    subtitle: 'Карамель · лава',
    description: 'Карамелизированное печенье Biscoff с тёплой лавой внутри.',
    structure: 'Хруст снаружи, текучая карамельная начинка внутри.',
    composition: 'Мука, спекулос-паста, сливочное масло, карамель, сахар, яйцо.',
    nutrition: { calories: 520, protein: 10, fat: 29, carbs: 60 },
  },
  salted: {
    subtitle: 'Солёная ириска',
    description: 'Солёная ириска и хруст — контраст сладкого и солёного.',
    structure: 'Плотная текстура с карамельными кусочками и морской солью.',
    composition: 'Мука, ириска, сливочное масло, морская соль, сахар, яйцо.',
    nutrition: { calories: 500, protein: 12, fat: 27, carbs: 56 },
  },
  cherry: {
    subtitle: 'Cherry Bloom',
    description: 'Вишнёвое печенье с насыщенной ягодной начинкой.',
    structure: 'Мягкое тесто с вишнёвым центром.',
    composition: 'Мука, вишня, сливочное масло, сахар, яйцо, ваниль.',
    nutrition: { calories: 475, protein: 14, fat: 23, carbs: 57 },
  },
} as const;

export const defaultCookies: Cookie[] = [
  {
    id: 'pistachio',
    name: 'Pistachio Berry Melt',
    ...COOKIE_DETAILS.pistachio,
    price: 380,
    images: ['/images/product-1.png'],
    active: true,
    sortOrder: 1,
  },
  {
    id: 'ferrero',
    name: 'Ferrero Core',
    ...COOKIE_DETAILS.ferrero,
    price: 360,
    images: ['/images/hits/product-ferrero.png'],
    active: true,
    sortOrder: 2,
  },
  {
    id: 'lemon',
    name: 'Lemon Berry Bliss',
    ...COOKIE_DETAILS.lemon,
    price: 350,
    images: ['/images/product-5.png'],
    active: true,
    sortOrder: 3,
  },
  {
    id: 'biscoff',
    name: 'Biscoff Lava',
    ...COOKIE_DETAILS.biscoff,
    price: 370,
    images: ['/images/hits/product-biscoff-69b495.png', '/images/hits/hits-cookie-overlay-5d98ac.png'],
    active: true,
    sortOrder: 4,
  },
  {
    id: 'salted',
    name: 'Salted Toffee Crunch',
    ...COOKIE_DETAILS.salted,
    price: 360,
    images: ['/images/hits/product-salted.png'],
    active: true,
    sortOrder: 5,
  },
  {
    id: 'cherry',
    name: 'Вишнёвое',
    ...COOKIE_DETAILS.cherry,
    price: 340,
    images: ['/images/boxes/cookie-cherry.png'],
    active: true,
    sortOrder: 6,
  },
];

export const defaultSets: CookieSet[] = [
  {
    id: 'hit-classic',
    name: 'Salted Toffee\nCrunch',
    image: '/images/hits/product-salted.png',
    price: 1400,
    items: [{ cookieId: 'salted', quantity: 4 }],
    featured: true,
    orderCount: 128,
    active: true,
    sortOrder: 1,
  },
  {
    id: 'hit-ferrero',
    name: 'Ferrero Core',
    image: '/images/hits/product-ferrero.png',
    price: 1400,
    items: [{ cookieId: 'ferrero', quantity: 4 }],
    featured: true,
    orderCount: 96,
    active: true,
    sortOrder: 2,
  },
  {
    id: 'hit-pistachio',
    name: 'Pistachio\nBerry Melt',
    image: '/images/product-1.png',
    price: 1520,
    items: [{ cookieId: 'pistachio', quantity: 4 }],
    featured: true,
    orderCount: 84,
    active: true,
    sortOrder: 3,
  },
  {
    id: 'hit-lemon',
    name: 'Lemon Berry\nBliss',
    image: '/images/product-5.png',
    price: 1400,
    items: [{ cookieId: 'lemon', quantity: 4 }],
    featured: true,
    orderCount: 72,
    active: true,
    sortOrder: 4,
  },
  {
    id: 'hit-biscoff',
    name: 'Biscoff\nLava',
    image: '/images/hits/product-biscoff-69b495.png',
    price: 1480,
    items: [{ cookieId: 'biscoff', quantity: 4 }],
    featured: true,
    orderCount: 55,
    active: true,
    sortOrder: 5,
  },
  {
    id: 'hit-cherry',
    name: 'Вишнёвое',
    image: '/images/boxes/cookie-cherry.png',
    price: 1360,
    items: [{ cookieId: 'cherry', quantity: 4 }],
    featured: true,
    orderCount: 40,
    active: true,
    sortOrder: 6,
  },
  {
    id: 'mix-signature',
    name: 'Signature Mix',
    image: '/images/boxes/size-signature.png',
    price: 2000,
    items: [
      { cookieId: 'pistachio', quantity: 2 },
      { cookieId: 'ferrero', quantity: 2 },
      { cookieId: 'biscoff', quantity: 2 },
    ],
    featured: false,
    orderCount: 45,
    active: true,
    sortOrder: 7,
  },
  {
    id: 'mix-party',
    name: 'Party Assortment',
    image: '/images/boxes/size-party.png',
    price: 3800,
    items: [
      { cookieId: 'pistachio', quantity: 3 },
      { cookieId: 'ferrero', quantity: 3 },
      { cookieId: 'lemon', quantity: 2 },
      { cookieId: 'salted', quantity: 2 },
      { cookieId: 'biscoff', quantity: 2 },
    ],
    featured: false,
    orderCount: 31,
    active: true,
    sortOrder: 8,
  },
];
